from fastapi import FastAPI, Depends, HTTPException, UploadFile, File, Form
from sqlalchemy.orm import Session
from typing import List, Optional
from datetime import datetime
import models
from db import get_db, init_db
from pydantic import BaseModel
import base64

app = FastAPI()

# Pydantic Models for Request Bodies
class UserLogin(BaseModel):
    email: str
    password: str

class UserRegister(BaseModel):
    username: str
    email: str
    password: str

class CRMInstanceCreate(BaseModel):
    username: str
    brand_name: str
    brand_color: str
    # Logo handled via UploadFile

class BillingEntry(BaseModel):
    customer_name: str
    item_name: str
    cost: float
    quantity: int

class WorkerCreate(BaseModel):
    name: str
    email: str
    phone: str
    address: str
    worker_type: str
    salary: float

class AttendanceEntry(BaseModel):
    id: int
    name: str
    type: str # worker_type
    status: str

class ExpenseCreate(BaseModel):
    category: str
    description: str
    amount: float
    user: str

class SalesOrderCreate(BaseModel):
    customer: str
    amount: float
    status: str

class CampaignCreate(BaseModel):
    name: str
    audience: str
    budget: float
    status: str

class RentalBookingCreate(BaseModel):
    name: str
    room: str
    rent: float
    deposit: float
    phone: str

class RestaurantSaleCreate(BaseModel):
    table_no: int
    items: str
    amount: float
    mode: str

class LeadCreate(BaseModel):
    name: str
    email: str
    source: str
    status: str

class LeaveRequestCreate(BaseModel):
    name: str
    l_type: str
    days: int

class PayrollCreate(BaseModel):
    name: str
    month: str
    amount: float

class InvoiceCreate(BaseModel):
    customer: str
    amount: float
    due_date: str
    status: str

# Initialize DB
@app.on_event("startup")
def on_startup():
    init_db()

@app.get("/")
def read_root():
    return {"message": "API is running"}

# Auth
@app.post("/register")
def register(user: UserRegister, db: Session = Depends(get_db)):
    db_user = db.query(models.User).filter(models.User.email == user.email).first()
    if db_user:
        raise HTTPException(status_code=400, detail="Email already registered")
    new_user = models.User(username=user.username, email=user.email, password=user.password)
    db.add(new_user)
    db.commit()
    return {"message": "User registered"}

@app.post("/login")
def login(user: UserLogin, db: Session = Depends(get_db)):
    db_user = db.query(models.User).filter(models.User.email == user.email, models.User.password == user.password).first()
    if db_user:
        return {"username": db_user.username}
    raise HTTPException(status_code=400, detail="Invalid credentials")

# CRM
@app.post("/crm/instance")
def create_crm_instance(
    username: str = Form(...),
    brand_name: str = Form(...),
    brand_color: str = Form(...),
    logo: UploadFile = File(None),
    db: Session = Depends(get_db)
):
    logo_bytes = logo.file.read() if logo else None
    new_instance = models.CRMInstance(
        instance_user=username,
        brand_name=brand_name,
        brand_color=brand_color,
        logo=logo_bytes
    )
    db.add(new_instance)
    db.commit()
    return {"message": "CRM Instance Created"}

@app.get("/crm/instance/{username}")
def get_crm_instance(username: str, db: Session = Depends(get_db)):
    instance = db.query(models.CRMInstance).filter(models.CRMInstance.instance_user == username).order_by(models.CRMInstance.id.desc()).first()
    if instance and instance.logo:
        logo_b64 = base64.b64encode(instance.logo).decode('utf-8')
    else:
        logo_b64 = None
        
    if instance:
        return {
            "brand_name": instance.brand_name,
            "brand_color": instance.brand_color,
            "logo": logo_b64
        }
    return {}

# Billing
@app.post("/billing")
def add_billing(entry: BillingEntry, db: Session = Depends(get_db)):
    new_bill = models.Billing(
        customer_name=entry.customer_name,
        item_name=entry.item_name,
        cost=entry.cost,
        quantity=entry.quantity,
        # customer_id generated by DB sequence or random if needed
    )
    db.add(new_bill)
    db.commit()
    return {"message": "Bill Saved"}

@app.get("/billing")
def get_billing(db: Session = Depends(get_db)):
    # Original logic returned tuples with days/years. 
    # We will return list of objects and let frontend handle display
    bills = db.query(models.Billing).order_by(models.Billing.date_of_entering.desc()).all()
    return bills

# Workers
@app.post("/workers")
def add_worker(worker: WorkerCreate, db: Session = Depends(get_db)):
    new_worker = models.Worker(
        name=worker.name,
        email=worker.email,
        phone_number=worker.phone,
        address=worker.address,
        worker_type=worker.worker_type,
        salary=worker.salary
    )
    db.add(new_worker)
    db.commit()
    db.refresh(new_worker)
    return {"message": f"Worker Added! ID: {new_worker.worker_id}"} # Returning generated ID

@app.get("/workers")
def get_workers(only_active: bool = False, db: Session = Depends(get_db)):
    query = db.query(models.Worker)
    if only_active:
        query = query.filter(models.Worker.removed_date == None)
    return query.all()

@app.put("/workers/{worker_id}/fire")
def fire_worker(worker_id: int, db: Session = Depends(get_db)):
    worker = db.query(models.Worker).filter(models.Worker.worker_id == worker_id).first()
    if not worker:
        raise HTTPException(status_code=404, detail="Worker not found")
    worker.removed_date = datetime.now()
    db.commit()
    return {"message": "Worker Fired"}

# Attendance
@app.post("/attendance")
def save_attendance(data: List[AttendanceEntry], db: Session = Depends(get_db)):
    count = 0
    for row in data:
        att = models.Attendance(
            worker_id=row.id,
            worker_name=row.name,
            worker_type=row.type,
            status=row.status
        )
        db.add(att)
        count += 1
    db.commit()
    return {"message": f"Marked attendance for {count} workers"}

@app.get("/attendance")
def get_attendance(db: Session = Depends(get_db)):
    return db.query(models.Attendance).order_by(models.Attendance.date.desc()).all()

# Expenses
@app.post("/expenses")
def add_expense(exp: ExpenseCreate, db: Session = Depends(get_db)):
    new_exp = models.Expense(
        category=exp.category,
        description=exp.description,
        amount=exp.amount,
        submitted_by=exp.user
    )
    db.add(new_exp)
    db.commit()
    return {"message": "Expense Logged"}

@app.get("/expenses")
def get_expenses(db: Session = Depends(get_db)):
    return db.query(models.Expense).order_by(models.Expense.expense_date.desc()).all()

# Sales
@app.post("/sales")
def add_sale(sale: SalesOrderCreate, db: Session = Depends(get_db)):
    new_sale = models.SalesOrder(
        customer_name=sale.customer,
        amount=sale.amount,
        status=sale.status
    )
    db.add(new_sale)
    db.commit()
    return {"message": "Order Created"}

@app.get("/sales")
def get_sales(db: Session = Depends(get_db)):
    return db.query(models.SalesOrder).order_by(models.SalesOrder.order_date.desc()).all()

# Ledger
@app.get("/ledger")
def get_ledger(db: Session = Depends(get_db)):
    return db.query(models.Ledger).all()

# Campaigns
@app.post("/campaigns")
def add_campaign(camp: CampaignCreate, db: Session = Depends(get_db)):
    new_camp = models.Campaign(
        campaign_name=camp.name,
        target_audience=camp.audience,
        budget=camp.budget,
        status=camp.status
    )
    db.add(new_camp)
    db.commit()
    return {"message": "Campaign Launched"}

@app.get("/campaigns")
def get_campaigns(db: Session = Depends(get_db)):
    return db.query(models.Campaign).all()

# Rental
@app.post("/rental")
def add_rental(booking: RentalBookingCreate, db: Session = Depends(get_db)):
    new_booking = models.RentalBooking(
        tenant_name=booking.name,
        room_number=booking.room,
        monthly_rent=booking.rent,
        security_deposit=booking.deposit,
        phone=booking.phone
    )
    db.add(new_booking)
    db.commit()
    return {"message": "Tenant Booked"}

@app.post("/rental/vacate")
def vacate_rental(room_number: str, db: Session = Depends(get_db)):
    # Note: room_number param is query param or body? Using Query for simplicity
    booking = db.query(models.RentalBooking).filter(
        models.RentalBooking.room_number == room_number, 
        models.RentalBooking.status == 'Occupied'
    ).first()
    if booking:
        booking.status = 'Vacated'
        booking.vacate_date = datetime.now()
        db.commit()
        return {"message": f"Room {room_number} Vacated"}
    raise HTTPException(status_code=404, detail="Room not found or already vacated")

@app.get("/rental")
def get_rental(status: str = "All", db: Session = Depends(get_db)):
    query = db.query(models.RentalBooking)
    if status != "All":
        query = query.filter(models.RentalBooking.status == status)
    return query.order_by(models.RentalBooking.join_date.desc()).all()

# Restaurant
@app.post("/restaurant/sales")
def add_restaurant_sale(sale: RestaurantSaleCreate, db: Session = Depends(get_db)):
    new_sale = models.RestaurantSale(
        table_number=sale.table_no,
        items_ordered=sale.items,
        total_amount=sale.amount,
        payment_mode=sale.mode
    )
    db.add(new_sale)
    db.commit()
    return {"message": "Bill Saved"}

@app.get("/restaurant/sales")
def get_restaurant_sales(db: Session = Depends(get_db)):
    return db.query(models.RestaurantSale).order_by(models.RestaurantSale.sale_date.desc()).all()

# Marketing Leads
@app.post("/leads")
def add_lead(lead: LeadCreate, db: Session = Depends(get_db)):
    new_lead = models.Lead(
        lead_name=lead.name,
        email=lead.email,
        source=lead.source,
        status=lead.status
    )
    db.add(new_lead)
    db.commit()
    return {"message": "Lead Added"}

@app.get("/leads")
def get_leads(db: Session = Depends(get_db)):
    return db.query(models.Lead).order_by(models.Lead.created_date.desc()).all()

# HR Leaves
@app.post("/hr/leaves")
def add_leave(leave: LeaveRequestCreate, db: Session = Depends(get_db)):
    new_leave = models.LeaveRequest(
        worker_name=leave.name,
        leave_type=leave.l_type,
        days=leave.days
    )
    db.add(new_leave)
    db.commit()
    return {"message": "Leave Request Sent"}

@app.get("/hr/leaves")
def get_leaves(db: Session = Depends(get_db)):
    return db.query(models.LeaveRequest).order_by(models.LeaveRequest.request_date.desc()).all()

# HR Payroll
@app.post("/hr/payroll")
def add_payroll(pay: PayrollCreate, db: Session = Depends(get_db)):
    new_pay = models.Payroll(
        worker_name=pay.name,
        salary_month=pay.month,
        amount_paid=pay.amount
    )
    db.add(new_pay)
    db.commit()
    return {"message": "Salary Processed"}

@app.get("/hr/payroll")
def get_payroll(db: Session = Depends(get_db)):
    return db.query(models.Payroll).order_by(models.Payroll.payment_date.desc()).all()

# Invoices
@app.post("/invoices")
def add_invoice(inv: InvoiceCreate, db: Session = Depends(get_db)):
    new_inv = models.Invoice(
        customer_name=inv.customer,
        amount=inv.amount,
        due_date=inv.due_date,
        status=inv.status
    )
    db.add(new_inv)
    db.commit()
    return {"message": "Invoice Created"}

@app.get("/invoices")
def get_invoices(db: Session = Depends(get_db)):
    return db.query(models.Invoice).order_by(models.Invoice.created_date.desc()).all()
